# Generated by Django 4.1.5 on 2023-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images'),
        ),
    ]
