# Generated by Django 4.1.5 on 2023-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_room_alter_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
